kubernetes pipeline improvements

diff --git a/deployments/basic-server-pipeline.yaml b/deployments/basic-server-pipeline.yaml
--- a/deployments/basic-server-pipeline.yaml
+++ b/deployments/basic-server-pipeline.yaml
@@ -9,7 +9,13 @@ resources:
   - name: kotlin-ktor-starter-image
     type: registry-image
     source:
-      repository: registry.${REGISTRY_DOMAIN}/kotlin-ktor-starter/kotlin-ktor-starter
+      repository: registry.${REGISTRY_DOMAIN}/kpack/kotlin-ktor-starter
+
+  - name: fresch-cloud-source-code
+    type: git
+    source:
+      uri: https://github.com/initialcapacity/freshcloud
+      branch: golang_spike
 
   - name: kotlin-ktor-starter-source-code
     type: git
@@ -25,6 +31,13 @@ resources:
       gke:
         json_key: ((service-account-key))
         kubeconfig: ((kubeconfig))
+
+  - name: kubernetes-task-image
+    type: registry-image
+    source:
+      repository: registry.${REGISTRY_DOMAIN}/concourse-images/cluster-mgmt
+      tag: latest
+
 jobs:
   - name: vulnerability-scan
     plan:
@@ -69,3 +82,54 @@ jobs:
       - put: kotlin-ktor-starter-build-service
         params:
           commitish: kotlin-ktor-starter-source-code/.git/ref
+
+  - name: deploy-kotlin-ktor-starter
+    plan:
+      - get: fresch-cloud-source-code
+      - get: kotlin-ktor-starter-source-code
+      - get: kotlin-ktor-starter-build-service
+        passed:
+          - vulnerability-scan
+        trigger: true
+      - get: kubernetes-task-image
+      - task: deploy-kubernetes
+        image: kubernetes-task-image
+        config:
+          platform: linux
+          inputs:
+            - name: fresch-cloud-source-code
+            - name: kotlin-ktor-starter-source-code
+          params:
+            KUBECONFIG: ((kubeconfig))
+            DOMAIN: ((domain))
+            GCP_PROJECT_ID: ((gcp_project_id))
+            GCP_ZONE: ((gcp_zone))
+            GCP_CLUSTER_NAME: ((gcp_cluster_name))
+            GCP_SERVICE_ACCOUNT_JSON: ((service_account_json))
+          run:
+            path: sh
+            args:
+            - -sc
+            - |
+              echo "${DOLLAR}KUBECONFIG" > config.yml
+              export KUBECONFIG=config.yml
+              export IMAGE=$(kubectl get image kotlin-ktor-starter-image -n kotlin-ktor-starter -o jsonpath="{.status.latestImage}")
+              envsubst < ./kotlin-ktor-starter-source-code/deployments/basic-server.yaml > basic-server.yaml
+              unset KUBECONFIG
+
+              export cred_file=$(mktemp)
+              trap "rm ${cred_file}" EXIT
+              echo "${DOLLAR}{GCP_SERVICE_ACCOUNT_JSON}" > ${DOLLAR}{cred_file}
+              chmod 600 ${DOLLAR}{cred_file}
+              gcloud auth login --cred-file "${DOLLAR}{cred_file}" --quiet
+              gcloud container clusters get-credentials ${DOLLAR}{GCP_CLUSTER_NAME} --zone ${DOLLAR}{GCP_ZONE} --project ${DOLLAR}{GCP_PROJECT_ID}
+              kubectl apply -f basic-server.yaml
+
+              echo "todo - use freshclt"
+              cd ./fresch-cloud-source-code/
+              go mod download && go mod verify
+              go run cmd/freshctl.go
+              if [ $? != 0 ]; then
+                echo "oops, failed to deploy."
+                exit 1
+              fi
